
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:token_db
    # Comment line above and uncomment line below to change from in-memory to file-based H2 DB
    # url: jdbc:h2:file:./data/token_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      # Change ddl-auto to 'update' to persist changes to the database between restarts
      ddl-auto: create-drop
      format_sql: true # Optional: Makes the logs much easier to read
      # Forces Hibernate to use the newer sequence generator behavior
#       id:
#         new_generator_mappings: true
#         # Helps Hibernate find the right schema in H2
#         default_schema: PUBLIC

# Note: If Spring detects an in-memory database jdbc:h2:mem:token_db is used, the default ddl-auto is: create-drop
# Behavior: It creates the tables and sequences when the app starts and deletes everything when the app shuts down.
# Reasoning: Since the memory is wiped anyway, Spring assumes you want a fresh, clean schema every time you run your
#            tests or local dev.
# Warning:
#  - Use this only for dev profile, be very careful when connecting to UAT/Prod database even when connecting to real DB
#
# For External Databases (PostgreSQL, MySQL, Oracle, etc.):
# - If Spring detects a "real" database driver, the default ddl-auto is: none
# - 'none' behavior: Spring will not attempt to create, update, or validate the database schema at all.

# Important limitations of ddl-auto: update to be aware of:
#  It will add new tables and columns ✅
#  It will NOT drop removed columns or tables ❌ — if you delete a field from your entity, the column stays in the DB
#  It will NOT rename columns — it sees a rename as "delete old + add new", so the old column stays and a new empty one is created
